---
# Variable setup.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define redis_package.
  ansible.builtin.set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis configuration dir exists.
  ansible.builtin.file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: '2770'

- name: Ensure Redis is configured.
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
  notify: Restart redis

- name: Get directory permissions
  ansible.builtin.stat:
    path: "{{ redis_conf_path | dirname }}"
  register: dir_stat

- name: Show directory permissions
  ansible.builtin.debug:
    msg: "Directory permissions are {{ dir_stat.stat.mode }}"

# Setup/install tasks.
- name: Include RedHat Setup Task
  ansible.builtin.include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian Setup Task
  ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Include ArchLinux Setup Task
  ansible.builtin.include_tasks: setup-archlinux.yml
  when: ansible_os_family == 'ArchLinux'

- name: Ensure Redis is running and enabled on boot.
  ansible.builtin.service:
    name: "{{ redis_daemon }}"
    state: started
    enabled: true
