---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Clear out repo for Fedora.
      ansible.builtin.set_fact:
        redis_enablerepo: ""
      when: ansible_distribution == 'Fedora'

  roles:
    - role: shaneholloman.redis
